site_name: Unify Documentation
site_url: https://unify-webapp.github.io/unify-docs/
theme:
  name: material
nav:
  - Getting Started: /unify-docs/
  - Tech stack: techstack/
  - Data Fetching (Context Creaton): datafetching/
  - Adding To The Docs: addingtodocs/
  
